### ISSUE TITLE
Can't Block/Love in 2.1

### ISSUE THREAD

**Issue by walterwh1te** [PsiLupan/MakeLobbiesGreatAgain#101]
Did you change the keybinds?

anyone else has this problem?

UsingWinPCap and latest Java

**Comment by adrianred** [comment]
I am having this same problem even after a clean install.

**Comment by folterung** [comment]
@PsiLupan, the instructions are a bit unclear on how to unblock. I have tried many different ways but still cannot seem to figure it out.

**Comment by PsiLupan** [comment]
Yeah, I have a feeling I broke it while removing some things.

Just stick to 1.39 for now.

**Comment by PsiLupan** [comment]
Corrected with 9b571786726cebfbe27e350a9b58fa6ea63f59f7.

Will update to the release this afternoon when I can compile and copy the JAR over.
