### ISSUE TITLE
Release 2.2's Notes

### ISSUE THREAD

**Issue by shadowmoose** [PsiLupan/MakeLobbiesGreatAgain#104]
Something seems wrong with the 2.2 release notes. It appears as though somebody tried to write them, but then suffered a brain contusion instead.

I'd offer some assistance in cleaning them up, but they're beyond help now.

**Comment by syminical** [comment]
There's also a popup telling me I'm a version behind, even though I download the version it points me to.

**Comment by PsiLupan** [comment]
It's fixed now @syminical
