### ISSUE TITLE
No base directory

### ISSUE THREAD

**Issue by Chimpboye** [PsiLupan/MakeLobbiesGreatAgain#105]
Either its not there or i cant find it, every time i re open mlga all blocks and loves are gone. Pls fix or tell me what im doing wrong

**Comment by Chimpboye** [comment]
I made the folder myself and now it works

**Comment by walterwh1te** [comment]
I have the same problem. Everytime i restart mlga all my blocked/loved are gone. @chimpboye where did you create the folder and how did you name it?

**Comment by PsiLupan** [comment]
The directory is C:\Users\[USERNAME]\AppData\Roaming\MLGA

If it can't create that directory, you have some type of permissions issue and your Windows install is likely starting to corrupt.

As far as I'm aware, that's not a protected folder, even if you're not an Admin user on your computer. It's supposed to allow your user access to that folder, as applications regularly write to it.
