### ISSUE TITLE
MLGA connecting to blocked lobbies

### ISSUE THREAD

**Issue by burabure** [PsiLupan/MakeLobbiesGreatAgain#109]
using the latest version of MLGA I still get connected to already blocked lobbies. Here's a video:

https://gfycat.com/unlawfulneedycommabutterfly

**Comment by CakeWizard** [comment]
I don't believe the purpose of MLGA is to avoid connecting you to blocked lobbies. It is to keep track of people you have blocked so you can dodge when necessary.

**Comment by jlnshr** [comment]
I think @CakeWizard is right. But only @PsiLupan can provide us on his intention with the blocking feature.

**Comment by PsiLupan** [comment]
That's correct - The block feature doesn't aim to prevent connections. It's just an early warning system.
