### ISSUE TITLE
Won't close

### ISSUE THREAD

**Issue by KingMundane** [PsiLupan/MakeLobbiesGreatAgain#111]
I for the life of me can't figure out how to close the program. It doesn't work if I put my compute to sleep, which I do everynight. So then when I try to use it the next day it say's no players always. so I have to move it or restart my cpu and reopen the program. is there a way to close the program without restarting my cpu?

**Comment by jlnshr** [comment]
In the [Readme.md](https://github.com/PsiLupan/MakeLobbiesGreatAgain/blob/master/README.md) it says:
> To exit, simply look for the icon in your system tray near the clock, right-click, and select Exit.
