### ISSUE TITLE
Doesnt work when internet goes over VPN not by LAN

### ISSUE THREAD

**Issue by iamoverit** [PsiLupan/MakeLobbiesGreatAgain#14]

**Comment by PsiLupan** [comment]
If you're using a VPN, it's encrypting more than likely. I can't fix that, unless there's a network interface that can be hooked for it.

I'll have to test with PIA and my work VPN, but odds are it won't happen.

**Comment by PsiLupan** [comment]
Yeah, can't hook a network interface and it's not working because of end-to-end encryption.
