### ISSUE TITLE
Issue with SFW hosting then joining lobby with killer, gets "stuck"

### ISSUE THREAD

**Issue by gawdsed** [PsiLupan/MakeLobbiesGreatAgain#15]
Here's my current setup where the issue happens and how to reproduce... I believe this is due to the killer addon as before, i had no issues with SWF

Scenario 1: Both me and my GF are playing on the same network(probably not relevant), I invite her, she joins. I join a killer game and the ping stays at 0. 

I then have to exit out of MLGA and launch it again to get the killer ping.

Scenario 2: She invites me, we start a game and join a killer, ping DOES show up.

Can we filer out the host IP if it's your own local network? I'm assuming it's connecting to the host in SFW and it detects it as a killer

**Comment by PsiLupan** [comment]
They may've changed the SWF lobby flow.

It used to be that when you joined an SWF lobby, it essentially acted like a Killer lobby. But upon joining a Killer's lobby for a match, it would disconnect the two of you and stop sending packets between each other.

I've written code that may fix it, but I'll need to get some people together for an SWF test at some point.

**Comment by gawdsed** [comment]
I'll check it now.

**Comment by gawdsed** [comment]
the one game i tried real quick worked.
