### ISSUE TITLE
Ping always says 0

### ISSUE THREAD

**Issue by WoodroweBones** [PsiLupan/MakeLobbiesGreatAgain#18]
I'm running windows 10. Is this a common issue on that OS?

Here is the info in the command window:

Version 1.22 :: Up to date!
Java Version: 1.8.0_121
Pcap Info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
22:41:26.418 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet, use default value: null
22:41:26.422 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet6, use default value: null
22:41:26.422 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.packet, use default value: null
22:41:26.422 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.link, use default value: null
22:41:26.428 [main] INFO org.pcap4j.core.Pcaps - 2 NIF(s) found.
Found: 192.168.19.83
Using IP from textfield: 192.168.19.83
22:41:28.116 [main] INFO org.pcap4j.core.Pcaps - 2 NIF(s) found.
22:41:28.127 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.dlt.raw, use default value: null
22:41:28.604 [main] INFO org.pcap4j.packet.factory.PacketFactories - Succeeded in FactoryBinder.getInstance()

**Comment by PsiLupan** [comment]
The warnings are because I don't have a properties file that sets anything. You can ignore the warnings.

**Comment by PsiLupan** [comment]
If you could, join a lobby while running the command prompt and see if anything shows up. There's not any debug lines, but if something throws an error, then I can resolve it. If nothing shows, I'll provide a debugging version.

I'm on Windows 10 and haven't experienced anything causing 0 ping unless I was using a VPN.

**Comment by WoodroweBones** [comment]
I had actually joined in and out of lobbies while it was open before I took the screenshot. The one thing I'm not convinced about is if Winpcap is working correctly. Let me know what I can do!

**Comment by PsiLupan** [comment]
Since it relies on STUN packets, my only thought is that possibly DMZ or open ports could prevent the need for STUN, though I find that doubtful.

I'll see if I can get a debug version built at some point to give you.

**Comment by antiks12** [comment]
I am also having this problem.  I've followed all the steps and also tried running through the batch file but no luck.  Would really like to use this after having my ability to check killers profiles taken away.

**Comment by PsiLupan** [comment]
Would either of you mind retesting with the latest release? Thanks.

**Comment by antiks12** [comment]
It works great now! Thanks so much
