### ISSUE TITLE
Doesn't work without LAN IP

### ISSUE THREAD

**Issue by Slayer00** [PsiLupan/MakeLobbiesGreatAgain#19]
I don't have modem, router or any device between my fiber connection and my PC which means that I don't have LAN IP or NAT or any kind of home network.

Is there any way to make the program work without an LAN IP address?
No matter what I choose it doesn't work, I have tried all 3 IPs it suggest for me.
My external IP address, default gateway and DHCP server.

**Comment by PsiLupan** [comment]
When you say default gateway and DHCP server, you're talking about the WAN side, right?

I literally don't have a way to test without a modem between (even at work, our fiber has an Adtran router), since it may be STUN packets aren't sent without the NAT.

**Comment by Slayer00** [comment]
Yes they are WAN and they are listed in ipconfig /all.

Now after I have rebooted the PC it gives me different IPs but none of them work.
Besides my external IP I have 198.18.14.38 and 192.168.56.1. I don't see those two in cmd->ipconfig /all and from what I understand from Google results 192.168.56.1 is the default IP assigned to a PC on some network and is a LAN IP but doesn't work for the ping indicator, it stays at 0.
Not entirely sure what the 198.18.14.38 is though, RCF manual says it's for testing locally connected devices.

**Comment by PsiLupan** [comment]
I think I may be able to do a test setup now, since I moved and have a separate router and modem. Will try in the near future.

**Comment by PsiLupan** [comment]
I made a change that may resolve the issue by removing uses of isSiteLocalAddress, which checks for things like 192/10 subnets or 127.0.0.1.

I'll need to actually test by using my WAN IP later this weekend,.

**Comment by Slayer00** [comment]
Still shows killer ping 0 after downloaded the latest version.

The IPs it shows me are:
198.18.15.90
192.168.56.1
and my external IP address

Tried them all, tried running as administrator but nothing worked.

**Comment by AbromofDarkAges** [comment]
After a big Windows Update, it now says in the LAN IP dropdown box "No devices found. Try running in Admin mode." I am an Administrator, and when I right click on the MLGA jar, the only thing it offers me to do as Admin is extract it. My Ipv4 is the same, which is the IP Address that this detected and used everytime before. When I enter it into MLGA's manual input box, it says that it doesn't exist.

**Comment by Slayer00** [comment]
Downloaded the latest version, replaced WinPcap with Npcap as per new install guide and now it works for me.
No modem or router, straight to fiber connection.

**Comment by PsiLupan** [comment]
Oh, sweet. Glad to hear it. Guess it was something at the driver level, which is odd, but I guess not unheard of.

I'll close this out then.
