### ISSUE TITLE
Getting 2 Different Errors

### ISSUE THREAD

**Issue by Xhaviour92** [PsiLupan/MakeLobbiesGreatAgain#27]
Hello Guys im trying since Hours get this to work i followed the guide 1 by 1

First Error : when i start it and enter my IP i get the Error :  The Device you selected doesent seem to exit. Double Check the IP you entered.

and when i try start it as admin i get the Error :  Error : unable to access jarfile Mlga.jar

i followed every step and came so far to the  MLGA Network Device Locate Window

and have

Select Lan IP obtained from Network Settings 
Any Unkown ip which i cant change

f your Device ip isnt the dropdown provide it below
i Inserted my Current IP

well and then i get the Error i wrote above

**Comment by PsiLupan** [comment]
Copy the directory MLGA.jar is in, like C:\Users\Dwight\Desktop\

Open the .bat file you made for Admin Mode. Edit it to look like:

cd C:\Path\You\Just\Copied
javaw -jar MLGA.jar

And that should let you run in Admin Mode.

**Comment by Xhaviour92** [comment]
this totaly not helped and dont even understood your explanation?

you mena have all files in same folder? if yeah i already had this and still not worked . also whats about the other problem?

**Comment by PsiLupan** [comment]
No, I mean the command "cd" changes which folder command prompt uses. It
thinks it is in C:\Windows\System32\ and it needs that command to work from
the directory MLGA is in.

The other error is caused by not running in Admin mode, and the fix above
is to make it so you can run Admin mode.
