### ISSUE TITLE
No NIF was found

### ISSUE THREAD

**Issue by HugoRiggs** [PsiLupan/MakeLobbiesGreatAgain#28]
One of the earlier versions worked for me, but on the latest I get this from execution:
```

PS C:\Users\InFlames\Downloads> java -jar '.\MLGA.jar'
Version 1.29 :: Up to date!
Java Version: 1.8.0_121
00:38:49.066 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Pcap Info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
00:38:49.701 [main] INFO org.pcap4j.core.Pcaps - No NIF was found.
```

**Comment by PsiLupan** [comment]
Just to make sure, was this debug run with Admin mode?

Also, you may want to see if making the switch to Npcap per the README changes anything.

**Comment by HugoRiggs** [comment]
I realized the installer was saying "failed to uninstall WinPcap", I uninstalled wireshark, which used WinPcap, and deleted Packet.dll from system32. After that Npcap was able to install correctly.
