### ISSUE TITLE
Idk.. it just didnt work, and jakes head cant be removed, cant end task since cant be selected.

### ISSUE THREAD

**Issue by tealtoxic** [PsiLupan/MakeLobbiesGreatAgain#29]
C:\Users\JONIDIPP\Desktop\Make Lobby Great Again>java -jar MLGA.jar
Version 1.29 :: Up to date!
Java Version: 1.8.0_131
20:22:39.145 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully lo
aded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
20:22:40.162 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet, use default value: 2
20:22:40.162 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet6, use default value: 23
20:22:40.162 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.packet, use default value: 17
20:22:40.162 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.link, use default value: 18
20:22:40.175 [main] INFO org.pcap4j.core.Pcaps - 12 NIF(s) found.
Found: Killer e2200 Gigabit Ethernet Controller (NDIS 6.30) ::: 192.168.0.100
Exception in thread "main" java.lang.NullPointerException
        at mlga.Boot.getLocalAddr(Boot.java:178)
        at mlga.Boot.main(Boot.java:58)

**Comment by PsiLupan** [comment]
It looks like threw the exception trying to get your device and check if it was up. Will push a release to resolve this afternoon.

**Comment by tealtoxic** [comment]
Works! :D thank you very much for your hard work.
