### ISSUE TITLE
No UI after startup

### ISSUE THREAD

**Issue by TheGamerXym** [PsiLupan/MakeLobbiesGreatAgain#30]
When I launch MLGA, the icon appears in my taskbar, but no UI appears of any sort. In addition, it can only be closed through the task manager; right clicking the icon and selecting "Exit" will do nothing.

I have made sure I have all necessary files installed, yet it still does not work. As a test, I deleted my mlga.preferences and mlga.settings to see if they would be remade, with only mlga.settings being recreated.

**Comment by PsiLupan** [comment]
Can you run following the debug steps in the README? That way a log can be provided to let me know what's happening.

It may be the same as an issue I closed earlier, which a fix is already in the pipe for, just not released yet.

**Comment by TheGamerXym** [comment]
[Here](http://puu.sh/vGL1i/89c674d74b.png)'s the image.

**Comment by PsiLupan** [comment]
Yup, same error as the issue earlier. It will be fixed in the following release, likely within the next 3 hours.

**Comment by TheGamerXym** [comment]
Awesome, thank you!
