### ISSUE TITLE
MLGA launches but has no UI after 1.29 release

### ISSUE THREAD

**Issue by allansramblings** [PsiLupan/MakeLobbiesGreatAgain#31]
Updated from the working 1.28 to 1.29 as directed by MLGA and now I have no UI at all. I can't exit MLGA through task bar and have to close through Task Manager. When launching 1.29 it doesn't ask for IP address like 1.28 did. Nothing happens upon launching 1.29 apart from the task bar Jake head.

**Comment by PsiLupan** [comment]
This is the same issue as the past 2 opened. It'll be resolved with the next release coming in ~3 hours.

**Comment by allansramblings** [comment]
<3
