### ISSUE TITLE
 Please make old version available.

### ISSUE THREAD

**Issue by hhofi** [PsiLupan/MakeLobbiesGreatAgain#32]
Thank you for always looking at the producer's lack of program shortage and care. 
However, it is cumbersome to get a new program every so often. 
Please make old version available too.

**Comment by PsiLupan** [comment]
Yeah, I'm not gonna do that. My intent was to push out the big changes this week and fix bugs that came up. 

It's pretty much gonna be every week or so from now on, if any updates, unless I feel a bug fix or feature is critical.
