### ISSUE TITLE
No Killer / Survivor IP since 1.3

### ISSUE THREAD

**Issue by Syrzan86** [PsiLupan/MakeLobbiesGreatAgain#33]
I can run it, it all worked with the last patches.
But since the new patch it always tells me either:
No Survivor or No Killer

It seems it can't detect any connection anymore for me.

Reinstalled Npcap and deleted Java and reinstalled it either. Nothing changes.

Ohh and it seems i can't exit normally anymore. Task manager to close process is the only way.

Did the bug issue thingy here is what it said.

Version 1.3 :: Up to date!
Java Version: 1.8.0_131
22:44:56.618 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully lo
aded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
22:44:58.029 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet, use default value: 2
22:44:58.030 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet6, use default value: 23
22:44:58.030 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.packet, use default value: 17
22:44:58.031 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.link, use default value: 18
22:44:58.066 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
Found: Realtek PCIe GBE Family Controller ::: 192.168.1.100
Found: Realtek PCIe GBE Family Controller ::: 192.168.1.100
Using IP from textfield: 192.168.1.100
22:45:24.028 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
22:45:24.035 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.dlt.raw, use default value: 12

I am clueless what this techblabla all means :-(

**Comment by PsiLupan** [comment]
Uhh, for some reason it found two of the same Ethernet cards. I'd imagine that's part of the issue.

**Comment by Syrzan86** [comment]
yeah but i cant change it.
but since 1.3 the choose ur ip thing doesnt show up every time... only once in a while and then i have two times my network card.

I tried to uninstall and reinstall all... i tried to set my pc back before i updated mlga. doesnt help either.

This last update ruined the whole thing for me somehow and i really don't know what to do about it.

**Comment by PsiLupan** [comment]
Hmm, 1.3 only fixed a bug related to devices that didn't respond with any info. Lemme try making a possible workaround, and I'll post a link to the patched JAR here for you  to test if it makes any difference.

**Comment by Syrzan86** [comment]
that would be awesome.

i should just say that it is 1am for me atm, so i might have a little bit delay cause of the time difference later on when i got to bed.

**Comment by PsiLupan** [comment]
https://drive.google.com/open?id=0B6khBzThTRKWUWgyM1BXaldubEE

Mind testing this version? I made a few changes to hopefully prevent the duplicate devices. I'd recommend wiping out the contents of your IP Address field and using the dropdown for testing.

**Comment by Syrzan86** [comment]
Still two times my Ethernet card detected, tried both dropdowns. Nothing.

Can still not close it via the Jake face... only through Taskmanager process ending

:-/

**Comment by PsiLupan** [comment]
Alright, can you run with the debug again and grab a log? This one should
provide me with a different log that might give me what I need.

**Comment by Syrzan86** [comment]
Here is the log i run.


Version 1.3 :: Up to date!
Java Version: 1.8.0_131
19:35:52.365 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully lo
aded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
19:35:53.930 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet, use default value: 2
19:35:53.931 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet6, use default value: 23
19:35:53.931 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.packet, use default value: 17
19:35:53.931 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.link, use default value: 18
19:35:53.949 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
Found: Realtek PCIe GBE Family Controller ::: 192.168.1.100
Found: Realtek PCIe GBE Family Controller ::: 192.168.1.100
Using IP from dropdown: 192.168.1.100
19:36:00.657 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
19:36:00.665 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.dlt.raw, use default value: 12

**Comment by PsiLupan** [comment]
Download the JAR file linked above again. It says it's 1.3 when it should be 1.31, meaning it must've been the wrong file.

**Comment by Syrzan86** [comment]
Hmm sry. still had the old file in my download folder. deleted all. tried the new one again still nothing

here is the log from the new:

Version 1.31 :: Up to date!
Java Version: 1.8.0_131
20:18:57.828 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully lo
aded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
20:18:59.230 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet, use default value: 2
20:18:59.237 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet6, use default value: 23
20:18:59.237 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.packet, use default value: 17
20:18:59.237 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.link, use default value: 18
20:18:59.270 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
Found: Realtek PCIe GBE Family Controller ::: 192.168.1.100
Found: Realtek PCIe GBE Family Controller ::: 192.168.1.100
Using device from dropdown: Realtek PCIe GBE Family Controller ::: 192.168.1.100

20:19:03.758 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
20:19:03.764 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.dlt.raw, use default value: 12

**Comment by PsiLupan** [comment]
Just uploaded a new one to the same link with some changes.

This time, it's going to show a number next to the device selection if both are shown. If you can try either number to see if there's a different result, that would be great.

**Comment by Syrzan86** [comment]
Version 1.31 :: Up to date!
Java Version: 1.8.0_131
21:20:35.399 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully lo
aded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
21:20:36.753 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet, use default value: 2
21:20:36.754 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet6, use default value: 23
21:20:36.754 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.packet, use default value: 17
21:20:36.754 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.link, use default value: 18
21:20:36.772 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
Found: 1 - Realtek PCIe GBE Family Controller ::: 192.168.1.100
Found: 2 - Realtek PCIe GBE Family Controller ::: 192.168.1.100
Using device from dropdown: 1 - Realtek PCIe GBE Family Controller ::: 192.168.1
.100
21:20:43.715 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
21:20:43.720 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.dlt.raw, use default value: 12



C:\Users\Martin\Downloads>java -jar MLGA.jar
Version 1.31 :: Up to date!
Java Version: 1.8.0_131
21:24:41.624 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully lo
aded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
21:24:43.010 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet, use default value: 2
21:24:43.011 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet6, use default value: 23
21:24:43.011 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.packet, use default value: 17
21:24:43.011 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.link, use default value: 18
21:24:43.026 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
Found: 1 - Realtek PCIe GBE Family Controller ::: 192.168.1.100
Found: 2 - Realtek PCIe GBE Family Controller ::: 192.168.1.100
Using device from dropdown: 2 - Realtek PCIe GBE Family Controller ::: 192.168.1
.100
21:24:50.590 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
21:24:50.596 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.dlt.raw, use default value: 12


and to be complete


C:\Users\Martin\Downloads>java -jar MLGA.jar
Version 1.31 :: Up to date!
Java Version: 1.8.0_131
21:25:14.962 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully lo
aded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
21:25:16.281 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet, use default value: 2
21:25:16.281 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.inet6, use default value: 23
21:25:16.281 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.packet, use default value: 17
21:25:16.281 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.af.link, use default value: 18
21:25:16.299 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
Found: 1 - Realtek PCIe GBE Family Controller ::: 192.168.1.100
Found: 2 - Realtek PCIe GBE Family Controller ::: 192.168.1.100
Using IP from textfield: 192.168.1.100
21:25:18.132 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
21:25:18.138 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.p
roperties] Could not get value by org.pcap4j.dlt.raw, use default value: 12

**Comment by PsiLupan** [comment]
Honestly, pretty stumped. The two interfaces is bizarre, and neither is a virtual interface. That's also the exact family of Ethernet that I have on my Mobo. Plus, there's no error that would indicate why it hangs.

As weird as it sounds, have you tried updating your Realtek drivers?

**Comment by Syrzan86** [comment]
Drivers are up to date.... but i saw in my hardware manager... that somehow my ethernet card is duplicated there too...

i think it might be my pc all in all.... just might have to erase all and start over with a cleaned pc
