### ISSUE TITLE
Doesn't work, or I'm doing something wrong?

### ISSUE THREAD

**Issue by daveimagery** [PsiLupan/MakeLobbiesGreatAgain#35]
Okay, I have MLGA installed, and appears to be running.  From what I have heard, it will show as "Blocked" for anyone you have blocked on steam.  Only it doesn't.  I've had numerous matches now with lagy killers who were on my steam block list, but MLGA doesn't indicate so.  It appears to me, you have to click on the killer's ping, and shift + left click to block while in-game.  BTW, the setup instructions are wrong, it's not "right click" it's left click.

**Comment by PsiLupan** [comment]
I can't block based on Steam blocklist, as I don't have access to the SteamAPI. The block is based on IP currently.

And thanks, I'll fix that.

**Comment by daveimagery** [comment]
Oh I see, makes sense.  Think I misunderstood how it works.  I will still use it, and thank you for your work.  :)
