### ISSUE TITLE
MLGA Doesn't Open

### ISSUE THREAD

**Issue by MajeoT** [PsiLupan/MakeLobbiesGreatAgain#36]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb9872fd0c, pid=3856, tid=0x0000000000002ed8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [d3d9.dll+0xfd0c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x000000001c355800):  JavaThread "AWT-Windows" daemon [_thread_in_native, id=11992, stack(0x000000001d3d0000,0x000000001d4d0000)]

siginfo: ExceptionCode=0xc0000005, writing address 0x0000000000000000

Registers:
RAX=0x0000000000000000, RBX=0x000000001d4cd800, RCX=0x000000002677a440, RDX=0x000000001d4ce010
RSP=0x000000001d4cd758, RBP=0x000000001d4cdaf0, RSI=0x0000000000000001, RDI=0x00000000267edf80
R8 =0x0000000000000000, R9 =0x0000000000000000, R10=0x000000002677b25c, R11=0x0000000000000246
R12=0x0000000000000002, R13=0x000000001d4ce010, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007ffb9872fd0c, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x000000001d4cd758)
0x000000001d4cd758:   00007ffb9873167f 000000001d4cd7b8
0x000000001d4cd768:   000000001d4cd7c0 00000000000006b0
0x000000001d4cd778:   0000000000010003 0000000000000000
0x000000001d4cd788:   00000000267edf80 0000000000000000
0x000000001d4cd798:   00007ffb987476a6 0000000000000000
0x000000001d4cd7a8:   0000000000000000 0000000000000001
0x000000001d4cd7b8:   0000000000000001 0000000000000000
0x000000001d4cd7c8:   0000000000000000 0000000000005c88
0x000000001d4cd7d8:   0000000000005c90 0000000000000000
0x000000001d4cd7e8:   000000001d4cd838 0000000000000000
0x000000001d4cd7f8:   000000000000001a 0000000000000000
0x000000001d4cd808:   0000000000000000 0000000028209240
0x000000001d4cd818:   000000002677a440 0000000000000000
0x000000001d4cd828:   000000000153d498 0000000000000000
0x000000001d4cd838:   0000000000000003 0000000000000000
0x000000001d4cd848:   0000000000000000 0000078000000048 

Instructions: (pc=0x00007ffb9872fd0c)
0x00007ffb9872fcec:   e9 10 fe ff ff cc cc cc cc cc cc cc cc cc cc cc
0x00007ffb9872fcfc:   cc cc cc cc ff 25 00 00 00 00 c0 96 01 80 01 00
0x00007ffb9872fd0c:   00 00 5c 24 20 55 56 57 41 54 41 55 41 56 41 57
0x00007ffb9872fd1c:   48 8d 6c 24 c0 48 81 ec 40 01 00 00 48 8b 05 a9 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000001d4cd800 is pointing into the stack for thread: 0x000000001c355800
RCX=0x000000002677a440 is an unknown value
RDX=0x000000001d4ce010 is pointing into the stack for thread: 0x000000001c355800
RSP=0x000000001d4cd758 is pointing into the stack for thread: 0x000000001c355800
RBP=0x000000001d4cdaf0 is pointing into the stack for thread: 0x000000001c355800
RSI=0x0000000000000001 is an unknown value
RDI=0x00000000267edf80 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x000000002677b25c is an unknown value
R11=0x0000000000000246 is an unknown value
R12=0x0000000000000002 is an unknown value
R13=0x000000001d4ce010 is pointing into the stack for thread: 0x000000001c355800
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value

Stack: [0x000000001d3d0000,0x000000001d4d0000],  sp=0x000000001d4cd758,  free space=1013k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [d3d9.dll+0xfd0c]
C  [d3d9.dll+0x1167f]
C  [d3d9.dll+0x276a6]
C  [d3d9.dll+0x2cb68]
C  [d3d9.dll+0x2a81e]
C  [awt.dll+0x19e2d]
C  [awt.dll+0x19f8b]
C  [awt.dll+0x1a93f]
C  [awt.dll+0x1e4c5]
C  [awt.dll+0x1b609]
C  0x00000000034b7f74

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.java2d.d3d.D3DGraphicsDevice.getDeviceCapsNative(I)I+0
j  sun.java2d.d3d.D3DGraphicsDevice.access$000(I)I+1
j  sun.java2d.d3d.D3DGraphicsDevice$1.run()V+8
v  ~StubRoutines::call_stub
j  sun.awt.windows.WToolkit.eventLoop()V+0
j  sun.awt.windows.WToolkit.run()V+58
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
=>0x000000001c355800 JavaThread "AWT-Windows" daemon [_thread_in_native, id=11992, stack(0x000000001d3d0000,0x000000001d4d0000)]
  0x000000001c355000 JavaThread "AWT-Shutdown" [_thread_blocked, id=11988, stack(0x000000001d2d0000,0x000000001d3d0000)]
  0x000000001bab8800 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=11804, stack(0x000000001d1d0000,0x000000001d2d0000)]
  0x000000001b6f3000 JavaThread "Keep-Alive-Timer" daemon [_thread_blocked, id=11996, stack(0x000000001bdd0000,0x000000001bed0000)]
  0x000000001a46d800 JavaThread "Service Thread" daemon [_thread_blocked, id=7276, stack(0x000000001af90000,0x000000001b090000)]
  0x000000001a3dd800 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=7288, stack(0x000000001ae90000,0x000000001af90000)]
  0x000000001a3d6800 JavaThread "C2 CompilerThread2" daemon [_thread_blocked, id=11984, stack(0x000000001ad90000,0x000000001ae90000)]
  0x000000001a3cb000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=6424, stack(0x000000001ac90000,0x000000001ad90000)]
  0x000000001a3c7800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=11968, stack(0x000000001ab90000,0x000000001ac90000)]
  0x000000001a3c6000 JavaThread "Attach Listener" daemon [_thread_blocked, id=12036, stack(0x000000001aa90000,0x000000001ab90000)]
  0x000000001a3c5000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=4200, stack(0x000000001a990000,0x000000001aa90000)]
  0x000000000349e000 JavaThread "Finalizer" daemon [_thread_blocked, id=7252, stack(0x000000001a7a0000,0x000000001a8a0000)]
  0x00000000184cd800 JavaThread "Reference Handler" daemon [_thread_blocked, id=3820, stack(0x000000001a2a0000,0x000000001a3a0000)]
  0x000000000339d800 JavaThread "main" [_thread_in_native, id=12124, stack(0x00000000031c0000,0x00000000032c0000)]

Other Threads:
  0x00000000184c9000 VMThread [stack: 0x000000001a1a0000,0x000000001a2a0000] [id=12028]
  0x000000001a481800 WatcherThread [stack: 0x000000001b090000,0x000000001b190000] [id=7280]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 38400K, used 28067K [0x00000000d5780000, 0x00000000d8200000, 0x0000000100000000)
  eden space 33280K, 84% used [0x00000000d5780000,0x00000000d72e8e38,0x00000000d7800000)
  from space 5120K, 0% used [0x00000000d7d00000,0x00000000d7d00000,0x00000000d8200000)
  to   space 5120K, 0% used [0x00000000d7800000,0x00000000d7800000,0x00000000d7d00000)
 ParOldGen       total 87552K, used 0K [0x0000000080600000, 0x0000000085b80000, 0x00000000d5780000)
  object space 87552K, 0% used [0x0000000080600000,0x0000000080600000,0x0000000085b80000)
 Metaspace       used 11883K, capacity 12172K, committed 12544K, reserved 1060864K
  class space    used 1338K, capacity 1432K, committed 1536K, reserved 1048576K

Card table byte_map: [0x0000000012860000,0x0000000012c60000] byte_map_base: 0x000000001245d000

Marking Bits: (ParMarkBitMap*) 0x0000000058afc720
 Begin Bits: [0x0000000013710000, 0x00000000156f8000)
 End Bits:   [0x00000000156f8000, 0x00000000176e0000)

Polling page: 0x0000000001460000

CodeCache: size=245760Kb used=4217Kb max_used=4233Kb free=241542Kb
 bounds [0x00000000034a0000, 0x00000000038d0000, 0x00000000124a0000]
 total_blobs=1565 nmethods=1128 adapters=349
 compilation: enabled

Compilation events (10 events):
Event: 1.254 Thread 0x000000001a3dd800 1125       3       java.util.logging.LogManager::getProperty (9 bytes)
Event: 1.254 Thread 0x000000001a3dd800 nmethod 1125 0x00000000038bc350 code [0x00000000038bc4c0, 0x00000000038bc6e8]
Event: 1.254 Thread 0x000000001a3dd800 1124       1       java.util.logging.LogManager::access$500 (5 bytes)
Event: 1.254 Thread 0x000000001a3dd800 nmethod 1124 0x00000000038bc090 code [0x00000000038bc1e0, 0x00000000038bc2d0]
Event: 1.256 Thread 0x000000001a3dd800 1126       1       java.util.Locale::getDefault (4 bytes)
Event: 1.256 Thread 0x000000001a3dd800 nmethod 1126 0x00000000038bbe10 code [0x00000000038bbf60, 0x00000000038bc050]
Event: 1.256 Thread 0x000000001a3dd800 1128       3       java.lang.ref.Reference::<init> (7 bytes)
Event: 1.256 Thread 0x000000001a3dd800 nmethod 1128 0x00000000038bb910 code [0x00000000038bba80, 0x00000000038bbd10]
Event: 1.256 Thread 0x000000001a3dd800 1127   !   3       java.util.logging.LogManager::ensureLogManagerInitialized (128 bytes)
Event: 1.257 Thread 0x000000001a3dd800 nmethod 1127 0x00000000038bacd0 code [0x00000000038bae80, 0x00000000038bb508]

GC Heap History (0 events):
No events

Deoptimization events (10 events):
Event: 0.296 Thread 0x000000000339d800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00000000036976b4 method=java.util.regex.Pattern$BmpCharProperty.match(Ljava/util/regex/Matcher;ILjava/lang/CharSequence;)Z @ 31
Event: 0.351 Thread 0x000000000339d800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x000000000367bd5c method=java.lang.CharacterDataLatin1.digit(II)I @ 82
Event: 0.351 Thread 0x000000000339d800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x000000000366d694 method=java.lang.CharacterDataLatin1.digit(II)I @ 82
Event: 0.636 Thread 0x000000000339d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000372b5c8 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 91
Event: 0.637 Thread 0x000000000339d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000372b5c8 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 91
Event: 1.121 Thread 0x000000000339d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000375acd8 method=java.io.DataInputStream.readInt()I @ 4
Event: 1.121 Thread 0x000000000339d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000375acd8 method=java.io.DataInputStream.readInt()I @ 4
Event: 1.121 Thread 0x000000000339d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000375acd8 method=java.io.DataInputStream.readInt()I @ 4
Event: 1.121 Thread 0x000000000339d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x000000000375acd8 method=java.io.DataInputStream.readInt()I @ 4
Event: 1.139 Thread 0x000000000339d800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000003757c04 method=java.util.regex.Matcher.search(I)Z @ 86

Internal exceptions (10 events):
Event: 1.129 Thread 0x000000000339d800 Exception <a 'java/io/FileNotFoundException'> (0x00000000d6dcd898) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.134 Thread 0x000000000339d800 Exception <a 'java/io/FileNotFoundException'> (0x00000000d6de1210) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.203 Thread 0x000000000339d800 Exception <a 'java/lang/NoSuchMethodError': org.slf4j.impl.StaticMDCBinder.getSingleton()Lorg/slf4j/impl/StaticMDCBinder;> (0x00000000d7144390) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\interpreter\linkRe
Event: 1.204 Thread 0x000000000339d800 Exception <a 'java/io/IOException'> (0x00000000d715b208) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.204 Thread 0x000000000339d800 Exception <a 'java/io/IOException'> (0x00000000d715b468) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.204 Thread 0x000000000339d800 Exception <a 'java/io/IOException'> (0x00000000d715b968) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.204 Thread 0x000000000339d800 Exception <a 'java/io/IOException'> (0x00000000d715bbf8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.204 Thread 0x000000000339d800 Exception <a 'java/io/IOException'> (0x00000000d715be58) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.209 Thread 0x000000000339d800 Exception <a 'java/io/FileNotFoundException'> (0x00000000d71700a0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.256 Thread 0x000000000339d800 Exception <a 'java/io/FileNotFoundException'> (0x00000000d725d740) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 1.280 loading class sun/java2d/pipe/RenderQueue done
Event: 1.280 loading class sun/java2d/d3d/D3DRenderQueue done
Event: 1.280 loading class sun/java2d/pipe/RenderBuffer
Event: 1.280 loading class sun/java2d/pipe/RenderBuffer done
Event: 1.280 loading class sun/java2d/d3d/D3DRenderQueue$1
Event: 1.280 loading class sun/java2d/d3d/D3DRenderQueue$1 done
Event: 1.281 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result
Event: 1.281 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result done
Event: 1.281 loading class sun/java2d/d3d/D3DGraphicsDevice$1
Event: 1.281 loading class sun/java2d/d3d/D3DGraphicsDevice$1 done

Dynamic libraries:
0x00007ff7818d0000 - 0x00007ff781907000 	C:\Program Files\Java\jre1.8.0_131\bin\javaw.exe
0x00007ffbc3a40000 - 0x00007ffbc3c1b000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffbc1180000 - 0x00007ffbc122e000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffbc0ce0000 - 0x00007ffbc0f29000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffbc10d0000 - 0x00007ffbc1171000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffbc15f0000 - 0x00007ffbc168d000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffbc39e0000 - 0x00007ffbc3a39000 	C:\WINDOWS\System32\sechost.dll
0x00007ffbc0fa0000 - 0x00007ffbc10c5000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffbc1690000 - 0x00007ffbc17da000 	C:\WINDOWS\System32\USER32.dll
0x00007ffbc0f80000 - 0x00007ffbc0f9e000 	C:\WINDOWS\System32\win32u.dll
0x00007ffbc18a0000 - 0x00007ffbc18c7000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffbc0b50000 - 0x00007ffbc0cd9000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffbc07e0000 - 0x00007ffbc087a000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffbc0a50000 - 0x00007ffbc0b46000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffbb8440000 - 0x00007ffbb86a7000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_108e4f62dfe5d999\COMCTL32.dll
0x00007ffbc3290000 - 0x00007ffbc3589000 	C:\WINDOWS\System32\combase.dll
0x00007ffbc0660000 - 0x00007ffbc06ca000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffbc1550000 - 0x00007ffbc157d000 	C:\WINDOWS\System32\IMM32.DLL
0x0000000059dc0000 - 0x0000000059e92000 	C:\Program Files\Java\jre1.8.0_131\bin\msvcr100.dll
0x00000000582e0000 - 0x0000000058b7c000 	C:\Program Files\Java\jre1.8.0_131\bin\server\jvm.dll
0x00007ffbc15e0000 - 0x00007ffbc15e8000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffbad300000 - 0x00007ffbad309000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffbbe290000 - 0x00007ffbbe2b3000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffbc1de0000 - 0x00007ffbc1e4c000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffbbb720000 - 0x00007ffbbb72a000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffbbdfd0000 - 0x00007ffbbdffb000 	C:\WINDOWS\SYSTEM32\winmmbase.dll
0x00007ffbc0f30000 - 0x00007ffbc0f79000 	C:\WINDOWS\System32\cfgmgr32.dll
0x0000000059db0000 - 0x0000000059dbf000 	C:\Program Files\Java\jre1.8.0_131\bin\verify.dll
0x0000000059d80000 - 0x0000000059da9000 	C:\Program Files\Java\jre1.8.0_131\bin\java.dll
0x0000000059d60000 - 0x0000000059d76000 	C:\Program Files\Java\jre1.8.0_131\bin\zip.dll
0x00007ffbc1e50000 - 0x00007ffbc3287000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffbc18d0000 - 0x00007ffbc197a000 	C:\WINDOWS\System32\shcore.dll
0x00007ffbbff60000 - 0x00007ffbc0652000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffbc1a00000 - 0x00007ffbc1a51000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffbbfed0000 - 0x00007ffbbfee1000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffbbff10000 - 0x00007ffbbff5c000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffbbfeb0000 - 0x00007ffbbfec5000 	C:\WINDOWS\System32\profapi.dll
0x00007ffbbf960000 - 0x00007ffbbf977000 	C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x00007ffbbf3e0000 - 0x00007ffbbf414000 	C:\WINDOWS\system32\rsaenh.dll
0x00007ffbbfa70000 - 0x00007ffbbfa95000 	C:\WINDOWS\SYSTEM32\bcrypt.dll
0x00007ffbbfdb0000 - 0x00007ffbbfdd9000 	C:\WINDOWS\SYSTEM32\USERENV.dll
0x00007ffbbf980000 - 0x00007ffbbf98b000 	C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x0000000059d40000 - 0x0000000059d5a000 	C:\Program Files\Java\jre1.8.0_131\bin\net.dll
0x00007ffbbf7c0000 - 0x00007ffbbf81c000 	C:\WINDOWS\system32\mswsock.dll
0x00007ffbbf560000 - 0x00007ffbbf597000 	C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x00007ffbc1c80000 - 0x00007ffbc1c88000 	C:\WINDOWS\System32\NSI.dll
0x00007ffbbb630000 - 0x00007ffbbb646000 	C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
0x00007ffbbb3c0000 - 0x00007ffbbb3da000 	C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
0x0000000059d20000 - 0x0000000059d31000 	C:\Program Files\Java\jre1.8.0_131\bin\nio.dll
0x00000000582b0000 - 0x00000000582d4000 	C:\Program Files\Java\jre1.8.0_131\bin\sunec.dll
0x0000000059d10000 - 0x0000000059d1b000 	C:\Program Files\Java\jre1.8.0_131\bin\sunmscapi.dll
0x00007ffbc0880000 - 0x00007ffbc0a49000 	C:\WINDOWS\System32\CRYPT32.dll
0x00007ffbbfef0000 - 0x00007ffbbff01000 	C:\WINDOWS\System32\MSASN1.dll
0x00007ffbbf5a0000 - 0x00007ffbbf644000 	C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x00007ffbb9e50000 - 0x00007ffbb9e5a000 	C:\Windows\System32\rasadhlp.dll
0x00007ffbb9f20000 - 0x00007ffbb9f8b000 	C:\WINDOWS\System32\fwpuclnt.dll
0x00007ffbb42c0000 - 0x00007ffbb4302000 	C:\Users\slync\AppData\Local\Temp\jna-109542133\jna4897672241338919040.dll
0x00007ffbb4250000 - 0x00007ffbb42b4000 	C:\WINDOWS\SYSTEM32\wpcap.dll
0x00007ffbb4220000 - 0x00007ffbb4250000 	C:\WINDOWS\SYSTEM32\packet.dll
0x00007ffbc3590000 - 0x00007ffbc39cb000 	C:\WINDOWS\System32\SETUPAPI.dll
0x00007ffbc1c90000 - 0x00007ffbc1dd4000 	C:\WINDOWS\System32\ole32.dll
0x0000000058110000 - 0x00000000582a8000 	C:\Program Files\Java\jre1.8.0_131\bin\awt.dll
0x00007ffbc17e0000 - 0x00007ffbc189f000 	C:\WINDOWS\System32\OLEAUT32.dll
0x00007ffbbe520000 - 0x00007ffbbe59e000 	C:\WINDOWS\SYSTEM32\apphelp.dll
0x00007ffbbe6d0000 - 0x00007ffbbe765000 	C:\WINDOWS\system32\uxtheme.dll
0x00007ffbc1230000 - 0x00007ffbc1396000 	C:\WINDOWS\System32\MSCTF.dll
0x0000000180000000 - 0x0000000180043000 	C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
0x0000000059770000 - 0x0000000059813000 	C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_08e667efa83ba076\MSVCR90.dll
0x00007ffbbd020000 - 0x00007ffbbd04a000 	C:\WINDOWS\system32\dwmapi.dll
0x00007ffbb40f0000 - 0x00007ffbb4211000 	C:\WINDOWS\system32\opengl32.dll
0x00007ffbb40c0000 - 0x00007ffbb40ec000 	C:\WINDOWS\SYSTEM32\GLU32.dll
0x00007ffb98720000 - 0x00007ffb988a9000 	C:\WINDOWS\system32\d3d9.dll
0x00007ffbbb060000 - 0x00007ffbbb13f000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_a2b0acab06663645\nvldumdx.dll
0x00007ffbc0780000 - 0x00007ffbc07d6000 	C:\WINDOWS\System32\WINTRUST.DLL
0x00007ffbc19e0000 - 0x00007ffbc19fd000 	C:\WINDOWS\System32\imagehlp.dll
0x00007ffb99510000 - 0x00007ffb9a525000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_a2b0acab06663645\nvd3dumx.dll
0x00007ffbb8260000 - 0x00007ffbb8431000 	C:\WINDOWS\system32\nvspcap64.dll
0x00007ffbb9560000 - 0x00007ffbb9637000 	C:\WINDOWS\SYSTEM32\WINHTTP.dll
0x00007ffbbccf0000 - 0x00007ffbbcd03000 	C:\WINDOWS\SYSTEM32\WTSAPI32.dll
0x00007ffbb60b0000 - 0x00007ffbb64d1000 	C:\WINDOWS\system32\nvapi64.dll
0x00007ffbbed20000 - 0x00007ffbbedc4000 	C:\WINDOWS\SYSTEM32\dxgi.dll
0x00007ffbbea30000 - 0x00007ffbbea58000 	C:\WINDOWS\System32\DEVOBJ.dll
0x00007ffbb9150000 - 0x00007ffbb9239000 	C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI64.dll
0x00007ffbb3c90000 - 0x00007ffbb3e39000 	C:\WINDOWS\SYSTEM32\dbghelp.dll

VM Arguments:
jvm_args: -Xverify:none 
java_command: F:\MLGA\MLGA.jar
java_class_path (initial): F:\MLGA\MLGA.jar
Launcher Type: SUN_STANDARD

Environment Variables:
_JAVA_OPTIONS=-Xverify:none
PATH=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Users\slync\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap
USERNAME=slync
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 15063 (10.0.15063.0)

CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 42 stepping 7, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, aes, clmul, ht, tsc, tscinvbit

Memory: 4k page, physical 8358120k(6186280k free), swap 18843880k(16020064k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.131-b11) for windows-amd64 JRE (1.8.0_131-b11), built on Mar 15 2017 01:23:53 by "java_re" with MS VC++ 10.0 (VS2010)

time: Mon May 08 18:28:45 2017
elapsed time: 1 seconds (0d 0h 0m 1s)

**Comment by PsiLupan** [comment]
https://www.java.com/en/download/help/exception_access.xml

**Comment by MajeoT** [comment]
Just want to add here that it wasn't to do with UAC as per the response above.

I ran the Java uninstall tool which was showing two versions of java installed, one had (64bit) in brackets, some googling shows that other applications have had problems with this so I removed it and now its loading, tested ingame as is working.
