### ISSUE TITLE
MLGA says I don't have Npcap installed when i do

### ISSUE THREAD

**Issue by Psych0R3d** [PsiLupan/MakeLobbiesGreatAgain#38]
MLGA used to work when i was at uni with an ethernet, and when i got home to play some dbd i went to launch it and i had to download 1.3. When i did so, i couldnt find my ip, maybe because im set up wirelessly here, so i tried to reinstall npcap to fix it. Now, when i click on MLGA.jar, it just gives me an error message saying i need to have either npcap or wincap installed. What do i do?

**Comment by PsiLupan** [comment]
Make sure you installed Npcap in "WinPcap compatibility mode" unless you've got your PATH setup for it.

**Comment by Psych0R3d** [comment]
Thank you cutie
