### ISSUE TITLE
Windows had a big update, now MLGA doesn't work

### ISSUE THREAD

**Issue by AbromofDarkAges** [PsiLupan/MakeLobbiesGreatAgain#39]
After a big Windows Update, it now says in the LAN IP dropdown box "No devices found. Try running in Admin mode." I am an Administrator, and when I right click on the MLGA jar, the only thing it offers me to do as Admin is extract it. My Ipv4 is the same, which is the IP Address that this detected and used everytime before. When I enter it into MLGA's manual input box, it says that it doesn't exist.

**Comment by PsiLupan** [comment]
Run As Admin is only possible by running the Command Prompt, like the README states.

You can also disable UAC if you are willing to take the security risk associated.

**Comment by AbromofDarkAges** [comment]
I found the ReadMe file on this site and did as it said, but it didn't help. I even tried it with a fresh MLGA download in a different folder, and it was the same results. I would run the batch file and it would say there was an error with it, and if I run it again, then it opens up the MLGA box like normal, but still does not recognize the IP address that I put in. Unfortunately, I don't have much patience for troubleshooting computer problems, so this is as far as I'm willing to take this. If this issue pops up with someone else, hopefully they can be of more help. I'll just do without MLGA for now. It was definitely nice while it lasted, so thank you for that :)

**Comment by PsiLupan** [comment]
If you tell me the error it gave on the batch file, I'll tell you how to
fix it. But yeah, past that I won't know till then.
