### ISSUE TITLE
Option for MLGA to dispay country_name instead.

### ISSUE THREAD

**Issue by Theholysonchrist** [PsiLupan/MakeLobbiesGreatAgain#4]
Just a small suggestion as this would lead to less guessing on the player's part as some country codes are a little more obscure than others. In those situations I feel country_name would be a lot clearer.

By the way, great work!

**Comment by PsiLupan** [comment]
Thanks, and this was planned but I hadn't gotten around to it due to blood hunt, since I wanted to spend more time farming than popping in and out of lobbies for tests.

I won't have a computer for about 5 days, so when I get back it'll be one of my first changes.

**Comment by PsiLupan** [comment]
Just committed with 1bf968f970a8701246a35e8120e5187a9a52c408 . It can be done by right-clicking.
