### ISSUE TITLE
Error. No Preferences were able to be loaded.

### ISSUE THREAD

**Issue by Delta141** [PsiLupan/MakeLobbiesGreatAgain#40]
???

**Comment by PsiLupan** [comment]
Means an IOException occured, so it couldn't create or read from the file.

Run in debug mode by following the README, then I can have something to review.

**Comment by Delta141** [comment]
The window that opens when I try to run the batch file (as admin and otherwise) immediately disappears before I can catch anything from it. :/

**Comment by PsiLupan** [comment]
Add PAUSE to the bottom of the batch file and it'll make it stay till you
press a key.

**Comment by Delta141** [comment]
C:\WINDOWS\system32>java -jar. MLGA.jar
Unrecognized option: -jar.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

C:\WINDOWS\system32>PAUSE
Press any key to continue . . .

**Comment by PsiLupan** [comment]
Remove the . after -jar

**Comment by Delta141** [comment]
C:\WINDOWS\system32>-jar MLGA.jar
'-jar' is not recognized as an internal or external command,
operable program or batch file.

**Comment by PsiLupan** [comment]
The proper command is java -jar MLGA.jar
