### ISSUE TITLE
No devices found. Try running in admin mode.

### ISSUE THREAD

**Issue by TemperrS** [PsiLupan/MakeLobbiesGreatAgain#41]
Before use the textfield:

Version 1.3 :: Up to date!
Java Version: 1.8.0_131
11:04:36.519 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
11:04:37.481 [main] INFO org.pcap4j.core.Pcaps - No NIF was found.

   After:

11:04:39.233 [main] INFO org.pcap4j.core.Pcaps - No NIF was found.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at mlga.Boot.main(Boot.java:68)
        ... 5 more

**Comment by PsiLupan** [comment]
Just to check, does this happen if you reboot your computer? I'm assuming you ran the .bat as Admin as well.

There's an issue where Pcap4j won't find devices till reboot.

**Comment by TemperrS** [comment]
I've tryed reboot the computer, reinstal npcap, and reinstal mlga when you said that before, i can try again but i dont think it will work. Yes i'm running as admin.

**Comment by TemperrS** [comment]
Rebooted and did what i said before some times and it still giving me the same problem :/

**Comment by PsiLupan** [comment]
I'll look into a possible fix. But honestly, that issue seems like the library or something resulting from the system.

I can't nail it down, since I've had multiple installs with no issue.

**Comment by TemperrS** [comment]
It works if you disable the uac with regedit and uninstall npcap and restart the pc every time you want to use mlga :v

**Comment by Crunchito** [comment]
i have  the same problem after doing the windows creators update...
i doubleclicked the the Npcap 0.86 installer for a reinstall ( he said something about a version is already installed. reinstall (possibly with different options)? i clicked yes and now every time the installation of npcap fails.... saying that pcap cant be uninstalled. i may need a little help here

**Comment by PsiLupan** [comment]
@TemperrS @Crunchito Can both of you try installing the latest version of Npcap and let me know the results?

Thanks.

**Comment by TemperrS** [comment]
@PsiLupan Worked for me. Thank you.

**Comment by PsiLupan** [comment]
Awesome, thanks for letting me know. Gonna close this out.
