### ISSUE TITLE
cant load

### ISSUE THREAD

**Issue by DeadHawky** [PsiLupan/MakeLobbiesGreatAgain#44]
i click start and It wont start since I updated it to 1.31

**Comment by PsiLupan** [comment]
Please follow this, and provide the log.

HOW TO SUBMIT A DEBUG LOG
(If you use an existing batch file, simply change javaw to java)
Right-click in the same directory as MLGA and create a new text document
Open it with Notepad and type: java -jar MLGA.jar
Choose Save As and name it MLGADebug.bat with the option All Files selected
Run the batch file
Submit a picture or copy of the text to an Issue
