### ISSUE TITLE
Auto-Updater?

### ISSUE THREAD

**Issue by exieln** [PsiLupan/MakeLobbiesGreatAgain#45]
I know the download speeds are fast, but sometimes people don't have the fastest speeds. It would be amazing if there was a background process checking for updates or on-launch it checks for updates.

**Comment by shadowmoose** [comment]
While an auto-updater would certainly be useful, it would certainly be a liability some people wouldn't like - pushing arbitrary code onto their machines.

It could possibly be implemented through a Settings toggle though, for the users who are okay with that.
