### ISSUE TITLE
[HELP] MLGA not working after update 

### ISSUE THREAD

**Issue by JuryoOfficial** [PsiLupan/MakeLobbiesGreatAgain#46]
So after the recent update of MLGA 1.31, the app no longer runs. MLGA worked perfectly fine before this update.

[MLGA Folder](https://puu.sh/vRTMd/88bf15a50d.png)
File path: `C:\Users\Juryo\Desktop\MLGA`

[Running MLGA](https://puu.sh/vRTNe/c7892f431f.png) (This problem happens when launching both the MLGA.bat and MLGA.jar)
`Unable to locate devices`
`Please try running the program in Admin Mode.`
`If this does not work, you may need to reboot your computer.`

[What my .bat file contains](https://puu.sh/vRTOW/711e96ea83.png)
`java -jar C:\Users\Juryo\Desktop\MLGA\MLGA.jar`

I'm currently running on Windows 10

Things I've tried already:

Recreating the .bat file
Redownloading MLGA
Removing every trace of MLGA and redownloading it
Restarting my computer
Checking for JAVA updates

When launching the .bat file with Administrator I get this log in my command prompt
`

> C:\WINDOWS\system32>java -jar C:\Users\Juryo\Desktop\MLGA\MLGA.jar
> Version 1.31 :: Up to date!
> Java Version: 1.8.0_101
> 12:34:34.886 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
> Pcap Info: WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
> 12:34:35.375 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet, use default value: 2
> 12:34:35.375 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet6, use default value: 23
> 12:34:35.376 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.packet, use default value: 17
> 12:34:35.376 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.link, use default value: 18
> 12:34:35.380 [main] WARN org.pcap4j.core.AbstractPcapAddress - Couldn't analyze an address. devName: {4CC86758-DCDF-4844-92F4-EE3732F3E4E8}, field: netmask, actual saFamily: -23536, expected saFamily: 2
> 12:34:35.403 [main] ERROR org.pcap4j.core.PcapNetworkInterface - Failed to retrieve the link layer address of the NIF: {4CC86758-DCDF-4844-92F4-EE3732F3E4E8}
> 12:34:35.403 [main] WARN org.pcap4j.core.AbstractPcapAddress - Couldn't analyze an address. devName: {FCB6C752-28F1-4891-9799-3032AC339E1F}, field: netmask, actual saFamily: -23536, expected saFamily: 2
> 12:34:35.423 [main] ERROR org.pcap4j.core.PcapNetworkInterface - Failed to retrieve the link layer address of the NIF: {FCB6C752-28F1-4891-9799-3032AC339E1F}
> 12:34:35.424 [main] WARN org.pcap4j.core.AbstractPcapAddress - Couldn't analyze an address. devName: {E43E9443-DA04-43CB-A775-37093E87ADA8}, field: netmask, actual saFamily: -23536, expected saFamily: 2
> 12:34:35.443 [main] ERROR org.pcap4j.core.PcapNetworkInterface - Failed to retrieve the link layer address of the NIF: {E43E9443-DA04-43CB-A775-37093E87ADA8}
> 12:34:35.444 [main] WARN org.pcap4j.core.AbstractPcapAddress - Couldn't analyze an address. devName: {CF524F61-E27A-43D3-9BA8-A0F1AEDD5056}, field: netmask, actual saFamily: -23536, expected saFamily: 2
> 12:34:35.464 [main] ERROR org.pcap4j.core.PcapNetworkInterface - Failed to retrieve the link layer address of the NIF: {CF524F61-E27A-43D3-9BA8-A0F1AEDD5056}
> 12:34:35.464 [main] INFO org.pcap4j.core.Pcaps - 4 NIF(s) found.

`

**Comment by PsiLupan** [comment]
The library isn't able to access your devices, though it at least sees them.

Right-click the JAR, go to Properties, and if there's anything below Attributes about blocking a file downloaded from the internet, choose Unblock.

**Comment by JuryoOfficial** [comment]
This is what I get when opening properties
[https://puu.sh/vRVaV/b96264c8d2.png](Image)

**Comment by PsiLupan** [comment]
Okay, looks like it's not blocking.

The only change I made was to get the MAC after it had already found your device instead of looking up that device again after. 

I'll try making a test version for you this afternoon to try and see if it resolves the issue.

**Comment by JuryoOfficial** [comment]
sounds good!

**Comment by foxthedog** [comment]
![526e4a7129e37e2d308ed2a9646f37b4](https://cloud.githubusercontent.com/assets/28762820/26167617/83efed0c-3b37-11e7-9cdf-db6362fc3876.png)^

Same problem here

**Comment by foxthedog** [comment]
Finaly i got it working  with that @WIN10 Pro

javaw -jar xxxx:\yyy\MLGA.jar

xxx is your harddisk
yyy is the folder
if you have intalled it in more subfolders use that like

xxx:\yyy\yyy\yyy\MLGA.jar

**Comment by V4nellope** [comment]
I'm experiencing the same issue, when I try to launch the MLGA

**Comment by MandyTalk** [comment]
I'm also having the same problem - I clicked unblock in the properties but it still won't start.

**Comment by Blazeflack** [comment]
I seem to be having the same issue. I downloaded this yesterday, but today it no longer works. This is what I get when running the .jar file in an elevated command prompt:

```
C:\WINDOWS\system32>java -jar C:\Users\Steffen\Desktop\MLGA\MLGA.jar
Version 1.31 :: Up to date!
Java Version: 1.8.0_131
14:50:24.819 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
14:50:24.955 [main] INFO org.pcap4j.core.Pcaps - No NIF was found.
```

**Comment by Blazeflack** [comment]
Alright I managed to get this working again. This is what I did:

1. Uninstall Npcap.
2. Reboot.
3. Look for traces of the following files, and moved them (didn't delete in case I had to restore them):
```
%WINDIR%\System32\Drivers\npcap.sys
%WINDIR%\System32\Drivers\npf.sys
```
4. Re-install Npcap.
5. Double-click MLGA.jar

**Comment by Blazeflack** [comment]
Another update:

Today it stopped working again. I suspect I have to go through the same un-install process as I outlined in my previous comment to fix it. Is there anything that can be done to fix this issue so we don't have to re-install Npcap every time we shutdown our computer?

**Comment by shadowmoose** [comment]
@Blazeflack To be clear, reinstalling the driver temporarily fixed the issue for you? 
Then after restarting, it failed to operate again?

**Comment by Blazeflack** [comment]
That is correct. If I shutdown my computer, then it won't work the next day.

To make it work I have to uninstall npcap, then do a reboot, then remove the 2 driver files I mentioned earlier, and finally re-install npcap. I have to repeat these exact steps to make it work if I turn my computer off.

**Comment by PsiLupan** [comment]
If you use WinPcap, do you have to do this at all? Both are compatible, and if one is less painful, well, I'd go with that.

**Comment by Blazeflack** [comment]
I didn't know I could use WinPcap as well. I will give that a try tomorrow and report back when I know the results.

Thanks.

**Comment by Blazeflack** [comment]
I removed Npcap and installed WinPcap 4.1.3 instead. This seems to have solved the problem for me. MLGA will now work correctly even after a computer shutdown/reboot without me having to re-install anything.

Thanks for the suggestion.
