### ISSUE TITLE
cant run MLGA after creators update.

### ISSUE THREAD

**Issue by Crunchito** [PsiLupan/MakeLobbiesGreatAgain#51]
i have a little problem after the windows creators update...
it said unable to locate devices ...blabla run in admin mode. i tried all that but it wont work. Then i doubleclicked the the Npcap 0.86 installer for a reinstall ( he said something about a version is already installed. reinstall (possibly with different options)? i clicked yes and now every time the installation of npcap fails.... saying that pcap cant be uninstalled. i may need a little help here.

**Comment by Crunchito** [comment]
i restarted a few time and i tried to run the .bat as admin as well

**Comment by Crunchito** [comment]
Version 1.31 :: Up to date!
Java Version: 1.8.0_131
20:23:12.878 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
20:23:13.238 [main] INFO org.pcap4j.core.Pcaps - No NIF was found.

**Comment by Blazeflack** [comment]
See this: https://github.com/PsiLupan/MakeLobbiesGreatAgain/issues/46#issuecomment-303097972

**Comment by Crunchito** [comment]
i deleted both files. and iam still getting this problem while installing:
![unbenannt](https://cloud.githubusercontent.com/assets/28872188/26327343/566c7c04-3f3f-11e7-9ccb-18868ce2d5c2.PNG)

**Comment by PsiLupan** [comment]
Start the computer in Safe Mode to uninstall it, just to see if that's the cause.

It may just be easier to revert to WinPcap.

**Comment by Crunchito** [comment]
when i want to install winPcap the computer says it already has a newer version installed... dunno how to deinstall it. i kinda dont know what to do here

**Comment by PsiLupan** [comment]
It thinks there's a newer version because of the NPCap install. Not sure how to fix it if you can't remove NPCap, even in Safe Mode.

**Comment by Crunchito** [comment]
i dont know how to remove NPCap its not event in the deinstall folder

**Comment by PsiLupan** [comment]
Said this on another issue, but try the latest version of NPCap. It may have addressed this.
