### ISSUE TITLE
Additional Options

### ISSUE THREAD

**Issue by PsiLupan** [PsiLupan/MakeLobbiesGreatAgain#54]
Look into adding a way to add things besides BLOCKED and LOVED through the settings INI, so people can customize it, such as Diatech wanting NURSE as an option.

**Comment by exieln** [comment]
it would be nice if we had killer and rank filters.

**Comment by Sincool** [comment]
that would be illegal. The devs wouldn't agree with it, they are hiding them for a reason.

**Comment by PsiLupan** [comment]
Even if I could do that, which I can't without cracking the game's encryption, I wouldn't.

**Comment by Blazeflack** [comment]
More options would be nice yeah. Personally I would like to be able to mark some as "Facecamping", "Tunneling", "Griefing", "Slugging" etc.

I may not want to dodge all these types, but it would allow me to know what I'm going into and be able to act accordingly.

**Comment by shadowmoose** [comment]
MLGA is for killers as well as survivors, and as far as I'm aware we've stepped away from this feature for a bit due to the implications of custom labels.

**Comment by Vascuas** [comment]
After today i would rather not block all the nurses, but set them as NURSE so i can decide if i want to have a boring match or not. I don't want to have all the nurse mains blocked, i don't mind fighting them every now and then but it upsets me i either have to block or ignore.
