### ISSUE TITLE
Use game's log file to associate IP with Steam ID

### ISSUE THREAD

**Issue by PsiLupan** [PsiLupan/MakeLobbiesGreatAgain#56]
Game spits out a log after it's​ closed with session information. This includes a lot of useful session information, but it's in-memory while the game is actually running.

We can build a running, encrypted log of IP to Steam ID, so that we can do error correction if people intentionally or not change IPs and are on the preferences. Or build it into preferences and have some way to upgrade from the old formatting.

**Comment by Blazeflack** [comment]
This sounds exciting. I imagine a lot of players are assigned dynamic IPs from their ISP, so a more precise blocklist would be amazing.

**Comment by shadowmoose** [comment]
This feature is currently completed under a development branch, pending further testing/release.

**Comment by Blazeflack** [comment]
Do you have a best estimate on when it might reach release state? Do you need help testing?

**Comment by PsiLupan** [comment]
It's currently nearly completed, we're just in the process of getting the
log check to verify against existing data.

**Comment by PsiLupan** [comment]
Feature is complete, pending small changes for the release tonight/tomorrow.
