### ISSUE TITLE
MLGA launching and closing

### ISSUE THREAD

**Issue by NecrosisX11** [PsiLupan/MakeLobbiesGreatAgain#57]
When I tried opening MLGA via it's icon, it appeared that Java opened an all black window and closed it in a fraction of a second. Following the author's steps at [https://dk.reddit.com/r/deadbydaylight/comments/6ejv4g/mlga_closes_on_startup/](url) caused a Command Prompt to run and the MLGA "No Killers" overlay to appear on my desktop.

Here is the debug screen. [<a href="http://imgur.com/1IdgsPd"><img src="http://i.imgur.com/1IdgsPd.png" title="source: imgur.com" /></a>](url)

**Comment by PsiLupan** [comment]
It looks like it's running just fine. No error and the "No killer" thing means you just haven't joined a match yet.

Run again with the normal "javaw" instead of "java" and remove the PAUSE. See if the UI opens still.
