### ISSUE TITLE
No Devices Found Error After Few Days of Running w/No Issue

### ISSUE THREAD

**Issue by Greyvane** [PsiLupan/MakeLobbiesGreatAgain#58]
![mlgascreendebug](https://cloud.githubusercontent.com/assets/29168251/26757381/a2eea9c0-4887-11e7-93bd-a431fa393f1f.PNG)
Worked fine for a few days, then suddenly was no longer able to find devices. Have uninstalled/reinstalled everything at least once. Tried to run as administrator, as well. No dice.

Issue persists in 1.33.
Issue persists in 1.35
Issue persists in 1.36

**Comment by PsiLupan** [comment]
Try grabbing the latest version of NPCap, and let me know if it does anything for you.

Thanks.

**Comment by Greyvane** [comment]
Sadly, no. Same debug screen. Java issue? Is my security software blocking it somehow?

**Comment by Greyvane** [comment]
Started playing around with the autoload settings, and got this error, mean anything?

![questionable screen](https://user-images.githubusercontent.com/29168251/27249685-25c8bd5c-52e9-11e7-9cd5-0ed078e46302.PNG)

**Comment by hsluoyz** [comment]
Hi @Greyvane , for the no NIC issue, can you test Npcap with Wireshark? If Wireshark sees interfaces with Npcap, then it should be Pcap4J's issue.

**Comment by Greyvane** [comment]
@hsluoyz Not sure how to do that. Downloaded Wireshark, and went through the list of 'capture using this filter' with all the options, but none of the options seemed to detect an interface. Not that I'm sure whether NPCap was even on that list or not.

**Comment by PsiLupan** [comment]
If Wireshark didn't show any interfaces, then it's likely a driver issue or something else happening.

You wouldn't see NPCap, you would see interfaces like "Ethernet" show up beneath your "Capture using this filter."
![wireshark](https://user-images.githubusercontent.com/7443598/27264422-9819650e-5443-11e7-9e66-720d3908d618.png)

**Comment by Greyvane** [comment]
Yah, this is what mine looks like. So I need to update a driver? Which one? >.<

![wireshark](https://user-images.githubusercontent.com/29168251/27264511-2cbb2c38-544e-11e7-8c72-c35f8ae0dcce.PNG)

**Comment by PsiLupan** [comment]
@hsluoyz is Npcap's developer, so he may want to debug with you as reporting no devices is serious issue.

I'd suggest installing WinPcap to see if there's any difference. If not, something else is happening.

**Comment by Greyvane** [comment]
@PsiLupan Yah... there was a difference all right. Wincap 4.1.3 was giving me the same errors as Npcap, so I searched around and found Win10Pcap, which I guess is for Windows 10, which is my OS, and my debug error message changed pretty drastically.

![debugwin10pcap](https://user-images.githubusercontent.com/29168251/27264878-621b66fa-5457-11e7-9c4c-71e357604d52.PNG)

And I've got stuff in my Wireshark now.

![wireshark](https://user-images.githubusercontent.com/29168251/27264884-8eb84d22-5457-11e7-9689-0b4cf2f7d0ed.PNG)

**Comment by Greyvane** [comment]
@PsiLupan 
@hsluoyz 

So, after uninstalling everything and then manually deleting all remaining files/registries, then doing another install of NpCap 0.92 and installing the latest MLGA (1.38) to my C: drive, everything works again. What a headache though. Win10Pcap really didn't want to uninstall, and NpCap refused to install in WinPCap compatibility mode until I could get rid of Win10Pcap. Thought I should let you know.

Still have no idea what the problem was, but manually wiping all files and trying again seems to do the trick.
