### ISSUE TITLE
Disabling network card causes high increase in CPU usage

### ISSUE THREAD

**Issue by Blazeflack** [PsiLupan/MakeLobbiesGreatAgain#59]
If you disable your network card while MLGA is running, then it will go from using very minimal CPU resources to suddenly use almost 40% (Core i5, 4 cores, 3.20GHz).

Re-enabling the network card does not make it use the normal amount of resources again, you have to exit the program and re-open it.

Disabling and re-enabling the network card will also cause MLGA to cease functioning until it is re-opened, but this may be an intended functionality.

**Comment by PsiLupan** [comment]
That's due to the driver losing connection with the device. 

Can't and won't fix it, since I have run into it before.
