### ISSUE TITLE
Newest Release (1.33) Not Showing Ping HUD Anymore

### ISSUE THREAD

**Issue by AbyssalDoom** [PsiLupan/MakeLobbiesGreatAgain#60]
Used to store my ping hud in the topleft corner of my screen, now unable to see or even identify where in the world it might be. Need help trying to get it back on screen.

**Comment by Madjong1** [comment]
Same thing :(

**Comment by MiraBear** [comment]
I got the same issue today
![image](https://user-images.githubusercontent.com/29292777/26955864-691896d6-4cc2-11e7-8c19-26318a5cc3ff.png)

**Comment by PsiLupan** [comment]
Is it working now? Pushed 1.34.

**Comment by Madjong1** [comment]
Its working for me on 1.35. Thank you very much!

**Comment by PsiLupan** [comment]
Awesome, going to close this out.

If you're still having issues, Abyssal, please open a new issue and try to provide the log file based on the README.

Thanks.
