### ISSUE TITLE
Error: Unable to access jarfile MLGA.jar

### ISSUE THREAD

**Issue by dedecconan** [PsiLupan/MakeLobbiesGreatAgain#61]
when I start the .bat file as admin, then it opens up a little window from Java Virtual Machine Launcher with the message in the title.

**Comment by PsiLupan** [comment]
You're not in the correct directory. Use the "cd" command to navigate to the directory that your MLGA.jar file is in. You can google that command.

**Comment by dedecconan** [comment]
the thing is there is no .jar file

**Comment by PsiLupan** [comment]
The file you download from the Releases page here is the .jar file.
