### ISSUE TITLE
Not Showing Ping Overlay

### ISSUE THREAD

**Issue by MiraBear** [PsiLupan/MakeLobbiesGreatAgain#63]
I can open MLGA normal, but the ping overlay is not showing
![image](https://user-images.githubusercontent.com/29292777/26956598-9a7af5b6-4cc7-11e7-9aef-bc8858c2d1fc.png)

**Comment by PsiLupan** [comment]
Your peers file is likely corrupted. Delete the peers.mlga file located in %APPDATA%/MLGA/

Leave the 1 - peers.mlga file, as it's a backup that it will attempt to load from.

**Comment by PsiLupan** [comment]
Issue should be resolved now. ShadowMoose hunted it down.
