### ISSUE TITLE
Can't install Npcap

### ISSUE THREAD

**Issue by BrettClaudio** [PsiLupan/MakeLobbiesGreatAgain#64]
In attempting to install Npcap, the installation is consistently aborted. I've attached the details from the Setup box. Any help would be appreciated.
![8115ad1cd0b39f7844088af70a8a30ef](https://user-images.githubusercontent.com/29384943/27051773-36140a0c-4f6c-11e7-839d-640aa48b3804.png)

**Comment by hsluoyz** [comment]
please see: https://github.com/nmap/nmap/issues/891

**Comment by BrettClaudio** [comment]
Thanks @hsluoyz. 

I attempted turning on System Protection but the option is greyed out for me. I can't select it.

**Comment by hsluoyz** [comment]
Then it should be your Windows OS issue, please google it for solutions.

**Comment by PsiLupan** [comment]
Did that work for you, @BrettClaudio ?

And thanks for looking at this, @hsluoyz
