### ISSUE TITLE
not working after Network Device window

### ISSUE THREAD

**Issue by icialote** [PsiLupan/MakeLobbiesGreatAgain#68]
First of all, My english is very poor.
Please understand me.

A few days ago. All fine. 
But yesterday, suddenly MLGA is no more working.
Not displayed 'No Player bar' after Network Device window.
Just Dwight Icon only.
Also Debug mod not working too.

http://i.imgur.com/VKnlwRk.png

**Comment by PsiLupan** [comment]
Change javaw to java, and the Debug mode will work.

**Comment by icialote** [comment]
I found problem.
But I don't know how to fix.

http://i.imgur.com/DhnWjkP.png

C:\Users\Arurung\AppData\Roaming\MLGA   
This 'MLGA' folder does not exist. I don't know why...but deleted...
anyway,  MLGA program is can't make new %appdata%\MLGA folder and peers.mlga and ect files.
please help me.

**Comment by PsiLupan** [comment]
I've implemented a fix for this in the next version, which should release tomorrow.

I'm going to close this issue, let me know if in the new version, it does not work for you still.
