### ISSUE TITLE
still same problem. (Issue #68)

### ISSUE THREAD

**Issue by icialote** [PsiLupan/MakeLobbiesGreatAgain#69]
same situation.
When I press the START button on the Network Device window,
'No Player' bar is not displayed.
but Debug message is little different.
MLGA is still can't make roaming\MLGA folder.

![mlga_00](https://user-images.githubusercontent.com/29587718/27505772-2f0d4dec-58e3-11e7-9cbb-db75854db300.png)

need advice.
thank you.

**Comment by PsiLupan** [comment]
Can you provide DeadByDaylight-nackup-2017.06.20-10.52.03.log file from:

%LocalAppData%/DeadByDaylight/saved/logs/

I'd like to see if this bug is caused by the fact your log may be in Korean.

**Comment by icialote** [comment]
I sent log file to your gmail.

**Comment by PsiLupan** [comment]
Thanks for that. I found the issue. The next version should fix the error at the bottom of that screenshot.

That's the only one that actually keeps MLGA from running.
