### ISSUE TITLE
MLGA not blocking BLOCKED killers.

### ISSUE THREAD

**Issue by Tathra365** [PsiLupan/MakeLobbiesGreatAgain#72]
Have just finished a game where I was put in with a killer that I had blocked via SHIFT + LEFT CLICK.  Did not notice before entering game so could not leave the game.  Please advise on what to do next.

Regards

Tathra

**Comment by Tathra365** [comment]
Forgot to mention I have the up-to-date MLGA as of 29/06/2017

**Comment by PsiLupan** [comment]
MLGA relies on the killer having either the same IP, or an IP logged in KINDRED (which you have to opt-in to use.)

Can't currently fix that without a  major rework that is kind of on the table.
