### ISSUE TITLE
KINDRED Alternative

### ISSUE THREAD

**Issue by PsiLupan** [PsiLupan/MakeLobbiesGreatAgain#74]
Investigate changing to other method using Steam log, rendering KINDRED invalid. This means:

1. Checking if Steam is active and/or prompting user to restart Steam.
2. See if we can pipe said logging directly into MLGA, whether by hooking the logging function with a DLL and using the JNA (unreliable due to Steam updates) or a virtual file, otherwise we'll need to prompt users to kill Steam when exiting MLGA then delete the file once done.
3. Parse the different log format
4. Convert legacy IDs to new format by writing the necessary formatter code. Should be extremely simple.

**Comment by Blazeflack** [comment]
Is this a contingency plan in case the DbD devs gives the thumbs down to Kindred, or are you planning on removing Kindred regardless?

**Comment by PsiLupan** [comment]
It's something that would replace it, assuming we had proper support. But
as it stands, it's a fallback.
