### ISSUE TITLE
1.39

### ISSUE THREAD

**Issue by Melty32** [PsiLupan/MakeLobbiesGreatAgain#77]
Ever since the latest update, 1.39, I've been having this error everytime I tried opening mlga, and I tried everything it suggested.
http://i.imgur.com/tOOznBH.png

**Comment by KwwB** [comment]
I'm having this exact same issue. Jar file is set to unblock. Haven't played DbD in around 2 months, just started playing again so I downloaded 1.39 and it is not working. Thanks for your work!

**Comment by PsiLupan** [comment]
Try Win10Pcap.
