### ISSUE TITLE
1.39 KINDRED asks for authentication every time I start MLGA.

### ISSUE THREAD

**Issue by chilopodab** [PsiLupan/MakeLobbiesGreatAgain#78]
My authentication code is being saved in the settings.ini and everything, but every time I start MLGA it takes me to the site to say I'm already logged in to copy the same code and paste it again.

**Comment by chilopodab** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10221993-182183853_26-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by shadowmoose** [comment]
Please post a log from MLGA when it starts, once you've posted your code in and booted.

**Comment by chilopodab** [comment]
How do I get the log? I checked my MLGA directory and the AppData folders.

**Comment by PsiLupan** [comment]
Run following the Debug steps on the README. It should show a command prompt window with the log.
