### ISSUE TITLE
Performance issue : FPS loss

### ISSUE THREAD

**Issue by L-2The-Ag** [PsiLupan/MakeLobbiesGreatAgain#80]
I've FPS loss when MLGA is running:

![image](https://user-images.githubusercontent.com/30640532/28852402-1bc511de-7729-11e7-8ffe-b19262fd25c2.png)
![image](https://user-images.githubusercontent.com/30640532/28852414-369fe1e6-7729-11e7-9ccc-b89bbc340c0b.png)
![image](https://user-images.githubusercontent.com/30640532/28852443-6ce857ec-7729-11e7-861a-6942de095765.png)
![image](https://user-images.githubusercontent.com/30640532/28852450-7dcffbf0-7729-11e7-838e-9a87dd9b4b33.png)

**Comment by PsiLupan** [comment]
Possibly an issue with people playing with unlocked frame rate. I've had people report this with the exact same hardware I have, but never checked if that was the cause.

The program only uses 1% CPU at maximum, so your computer has some kind of thread contention going on.
