### ISSUE TITLE
backups

### ISSUE THREAD

**Issue by Holywarz666** [PsiLupan/MakeLobbiesGreatAgain#81]
as i have noticed MLGA makes backups of your game data from time to time, but where do those backups go since my roommate caused my game to delete all it's data causing me to start from level 1 on all characters again. i've tried looking for the backups but i do not know where they are located. and even then, how to i apply the backup to my game to get my progress back.

**Comment by alui07** [comment]
https://steamcommunity.com/app/381210/discussions/0/1843493219431981208/#c1843493219432027305

Not sure about it in reference to MLGA, but if it's your first time losing data, you can contact the devs for a onetime reset. I don't know if this is enough information about MLGA backups, but here's a reddit post

https://www.reddit.com/r/deadbydaylight/comments/6deg1m/mlga_release_132_backup_in_action/

**Comment by Holywarz666** [comment]
Aye thank you so much, cause mlga had detected possible data lost it never replaced my backups so i got my data back. Which is great cause otherwise i would have never touched this game again, unless i was playing some private matches cause i have spent over 500 hours getting everything that i have now. I
appreciate you spending a couple seconds (or minutes cause i know people who type slow) to type your message to help with my problem. The fact that you spent time searching for those 2 links also shows you're dedication. Sorry if this reply was slow as i just noticed it now, i knew about the dev reset though. i saw a streamer get help from the devs from a bit of data loss by giving him BP based on his hours played.
