### ISSUE TITLE
MLGA backup system

### ISSUE THREAD

**Issue by smrtg** [PsiLupan/MakeLobbiesGreatAgain#83]
I've heard that mlga has a backup feature, mine doesn't. Did I do something wrong while installing or what?

**Comment by PsiLupan** [comment]
When you first started it, it would prompt you to enable.

You can look at your mlga.settings.ini and if backups is set to 0 instead of 1, then it's disabled.

**Comment by smrtg** [comment]
So I enabled it. Does it backup automatically or what? Cause I don't see
anything

**Comment by PsiLupan** [comment]
It backups everytime the game saves to %APPDATA%/MLGA/backups/, and if the
save looks like it's a fresh save and smaller than your previous, it will
throw a warning that your save corrupted.
