### ISSUE TITLE
MLGA says device does not exist

### ISSUE THREAD

**Issue by lilbluesiren** [PsiLupan/MakeLobbiesGreatAgain#88]
second time mlga decided to just randomly stop working for me.

**Comment by mazacik** [comment]
I also have this problem. Windows 8.1.
What I did:
Updated Java to the newest version (8/151)
Installed NpCap 0.96 with the WinPcap API-compatible Mode
Disabled UAC
Restarted my computer
Unblocked MLGA.jar in file properties
Started MLGA.jar through the command prompt as administrator
Got the error "Unable to locate devices. Please try running the program in Admin Mode."
Uninstalled NpCap, removed the leftover driver, deleted packet.dll, npf.sys and npcap.sys
Restarted
Installed WinPcap 4.1.3
Checked for the files I manually deleted, they were there.
Restarted again
Got the same error.

npf and npcap (when npcap was installed) services were up and running.

Log:
![mlga log](https://user-images.githubusercontent.com/19615998/33226499-99009ac2-d18f-11e7-854e-e79bf09af323.JPG)
The first part is probably my computer's fault and most likely doesn't affect MLGA functionality. The second part I don't understand at all.
