### ISSUE TITLE
Mlga doesnt open

### ISSUE THREAD

**Issue by Drostepp** [PsiLupan/MakeLobbiesGreatAgain#90]
It just flashes the command prompt really fast and nothing else happens

**Comment by PsiLupan** [comment]
Put PAUSE on the last line of your batch file, and it'll give the error. Odds are, it's that it doesn't see the JAR file in the directory.

**Comment by flootist** [comment]
I followed KyoDaz's MLGA install tutorial on Steam, and here is the error I have:

"[directory]\MLGA>java -jar MLGA.jar
'java' is not recognized as an internal or external command,
operable program or batch file."

How does one make the JAR file visible?

**Comment by PsiLupan** [comment]
@flootist Look up "Adding Java to PATH environment variable."

Your system isn't recognizing you have Java installed, so you have to adjust a Windows setting under the System settings on Control Panel.
