### ISSUE TITLE
MLGA Stopped working after new Windows Update ?

### ISSUE THREAD

**Issue by Kitto0** [PsiLupan/MakeLobbiesGreatAgain#91]
Updated Windows 10 to version 1709 & next thing i know, MLGA isn't working at all afterwards with error msg saying : 

"unable to locate devices please try to run the program in admin mode if this doesnt work, you may need to reboot the computer"

Any solution around this problem ???

**Comment by Nikedawg** [comment]
Yeah I had this happen too, I had to reinstall npcap to get it to work. The version I had was .94 I think but the site has a newer .95 version that made this error go away for me.

**Comment by PsiLupan** [comment]
Yeah, the newest Npcap fixes a known issue with Windows updates breaking the location they were installing files.
