### ISSUE TITLE
MLGA Backups not working

### ISSUE THREAD

**Issue by CyberStar1** [PsiLupan/MakeLobbiesGreatAgain#92]
Hello, 

Yesterday i downloaded the MLGA 1.39 addon and played dbd. Now i wanted to check if its making any backups but when i check the appdata roming folder there is no MLGA folder anywhere.

In the settings it says that its saving the backups to that location.

Any idea?

**Comment by CyberStar1** [comment]
EDIT: Manually created the folder now it has 2 files in it:

1- peers.mlga
peers.mlga 

Is this right?

**Comment by minora85** [comment]
i have the same problem. knows anyone why mlga doesn´t make backups? before the fall creator update (windows) it was working fine for me.
